{{- if .Values.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "hubot.fullname" . }}"
  labels:
    app: {{ template "hubot.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "hubot.name" . }}
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.budget.minAvailable }}
{{- end -}}
