{{- if .Values.ingress.enabled -}}
{{- $serviceName := include "wb.fullname" . -}}
{{- $servicePort := .Values.service.externalPort -}}
{{- $ingressPaths := .Values.ingress.paths -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "wb.fullname" . }}
  labels:
    app: {{ template "wb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- if .Values.maintenance.enabled }}
    {{- $serviceName := include "maintenance.fullname" . -}}
    {{- $servicePort := .Values.maintenance.service.externalPort -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end -}}
    {{- end -}}
    {{- else -}}
    {{- $serviceName := include "wb.fullname" . -}}
    {{- $servicePort := .Values.service.externalPort -}}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
          {{- end -}}
    {{- end -}}
    {{- end -}}
  {{- if (or .Values.ingress.tls (and .Values.certificate.enabled .Values.certificate.tls)) }}
  tls:
    {{- if .Values.ingress.tls }}
    {{- toYaml .Values.ingress.tls | nindent 4 }}
    {{- end -}}
    {{- if (and .Values.certificate.enabled .Values.certificate.tls) }}
    - secretName: "{{ template "wb.certificate.fullname" . }}"
      hosts:
        {{- range .Values.certificate.acmeConfig.domains }}
        - {{ . }}
        {{- end }}
    {{- end -}}
  {{- end -}}
{{- end -}}
