apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "http-redirect.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "http-redirect.fullname" . }}
spec:
{{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "http-redirect.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
