apiVersion: v1
description: Hubot chatbot
name: hubot
version: 0.1.0
icon: https://hubot.github.com/assets/images/layout/hubot-avatar@2x.png
keywords:
  - chat
  - hubot
sources:
  - https://github.com/CenterForOpenScience/hubot
maintainers:
  - name: Michael Haselton
    email: michael@cos.io
    url: https://github.com/icereval
  - name: Barrett Harber
    email: barrett@cos.io
    url: https://github.com/binoculars
engine: gotpl
tillerVersion: '>=2.7.0'