apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nessus.fullname" . }}
  labels:
    app: {{ template "nessus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.docker.imageCredentials.enabled }}
  .dockerconfigjson: {{ template "nessus.docker.imagePullSecret" . }}
  {{- end }}
  {{- range $key, $value := .Values.tls.files }}
  tls-{{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
