{{- if .Values.beat.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "lookit.beat.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.beat.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "lookit.name" . }}
        component: "{{ .Values.beat.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "lookit.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
        - name: {{ .Values.beat.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gosu
            - www-data
            - celery
            - -A
            - project.celery.app
            - beat
            - -l
            - DEBUG
            - --pidfile=
          env:
            {{- include "lookit.environment" . | indent 12 }}
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "lookit.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "lookit.fullname" . }}
      {{- if .Values.beat.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.beat.nodeSelector | nindent 8 }}
      {{- end }}
{{- end -}}
