{{- if .Values.builder.enabled -}}
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "lookit.builder.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.builder.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  serviceName: {{ template "lookit.builder.fullname" . }}
  replicas: {{ .Values.builder.replicaCount }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
        partition: 0
  template:
    metadata:
      labels:
        app: {{ template "lookit.name" . }}
        component: "{{ .Values.builder.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "lookit.deploymentAnnotations" . | indent 8 }}
    spec:
      containers:
        - name: docker
          image: "{{ .Values.builder.docker.image.repository }}:{{ .Values.builder.docker.image.tag }}"
          imagePullPolicy: {{ .Values.builder.docker.image.pullPolicy }}
          args:
            - --storage-driver=overlay
          ports:
            - name: docker
              containerPort: 2375
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-volume
            - mountPath: /code/ember_build/checkouts
              name: checkouts-volume
            - mountPath: /code/ember_build/deployments
              name: deployments-volume
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.builder.docker.resources | nindent 12 }}
        - name: {{ .Values.builder.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - gosu
            - www-data
            - celery
            - -A
            - project.celery.app
            - worker
            - -c
            - "{{ .Values.builder.concurrency }}"
            - -l
            - INFO
            - -n
            - worker.%h
            - --without-gossip
            - --maxtasksperchild
            - "{{ .Values.builder.maxTasksPerChild }}"
            - -Q
            - "{{ .Values.builder.queues }}"
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
            {{- include "lookit.environment" . | indent 12 }}
          volumeMounts:
            - mountPath: /code/ember_build/checkouts
              name: checkouts-volume
            - mountPath: /code/ember_build/deployments
              name: deployments-volume
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.builder.resources | nindent 12 }}
      volumes:
        {{- if not .Values.builder.persistence.enabled }}
        - name: docker-volume
          emptyDir: {}
        {{- end }}
        - name: checkouts-volume
          emptyDir: {}
        - name: deployments-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ template "lookit.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "lookit.fullname" . }}
    {{- if .Values.builder.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.builder.nodeSelector | nindent 8 }}
    {{- end }}
  {{- if .Values.builder.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: docker-volume
      spec:
        accessModes:
          - {{ .Values.builder.persistence.accessMode | quote }}
        {{- if .Values.builder.persistence.storageClass }}
        storageClassName: {{ .Values.builder.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.builder.persistence.size | quote }}
  {{- end }}
{{- end -}}