apiVersion: v1
kind: Secret
metadata:
  name: {{ template "lookit.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $value := .Values.secretEnvs }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- range $key, $value := .Values.secretFiles }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
