{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "lookit.web.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.web.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.externalPort }}
      targetPort: {{ .Values.web.service.internalPort }}
      protocol: TCP
      name: {{ .Values.web.service.name }}
  selector:
    app: {{ template "lookit.name" . }}
    component: "{{ .Values.web.name }}"
    release: {{ .Release.Name }}
{{- end -}}
