{{- if .Values.web.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "lookit.web.fullname" . }}"
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.web.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "lookit.name" . }}
      component: "{{ .Values.web.name }}"
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.web.budget.minAvailable }}
{{- end -}}
