{{- if .Values.web.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "lookit.web.fullname" . }}
  labels:
    app: {{ template "lookit.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.web.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "lookit.name" . }}
        component: "{{ .Values.web.name }}"
        release: {{ .Release.Name }}
      annotations:
        {{- include "lookit.deploymentAnnotations" . | indent 8 }}
    spec:
      {{- if not .Values.collectstatic.enabled }}
      initContainers:
        - name: {{ .Values.collectstatic.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - manage.py
            - collectstatic
            - --noinput
          env:
            {{- include "lookit.environment" . | indent 12 }}
          volumeMounts:
            - mountPath: /code/project/static
              name: static-volume
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      {{- end }}
      containers:
        - name: nginx
          image: "{{ .Values.web.nginx.image.repository }}:{{ .Values.web.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.web.nginx.image.pullPolicy }}
          command:
            - nginx
            - -c
            - /etc/nginx/nginx.conf
            - -g
            - daemon off;
          ports:
            - name: http
              containerPort: {{ .Values.web.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.web.service.internalPort }}
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /static
              name: static-volume
            - mountPath: /etc/nginx/nginx.conf
              name: config-volume
              subPath: nginx.conf
              readOnly: true
            - mountPath: /usr/share/nginx/html/robots.txt
              name: config-volume
              subPath: robots.txt
              readOnly: true
          resources:
            {{- toYaml .Values.web.nginx.resources | nindent 12 }}
        - name: uwsgi
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - uwsgi
            - --ini
            - /etc/uwsgi/uwsgi.ini
            - --socket
            - :{{ .Values.web.service.externalPort }}
          env:
            {{- include "lookit.environment" . | indent 12 }}
          ports:
            - name: wsgi
              containerPort: {{ .Values.web.service.externalPort }}
            - name: stats
              containerPort: 1717
          readinessProbe:
            tcpSocket:
              port: {{ .Values.web.service.externalPort }}
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /etc/uwsgi/uwsgi.ini
              name: config-volume
              subPath: uwsgi.ini
              readOnly: true
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: static-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: {{ template "lookit.fullname" . }}
        - name: secret-volume
          secret:
            secretName: {{ template "lookit.fullname" . }}
      {{- if .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.web.nodeSelector | nindent 8 }}
      {{- end }}
{{- end -}}
