apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    {{- include "redis.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
