# https://docs.sentry.io/server/installation/docker/#running-migrations
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-init"
  labels:
    {{- include "sentry.labels.standard" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-db-init"
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: db-init-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sentry
            - upgrade
            - --noinput
          env:
            {{- include "sentry.environment" . | nindent 12 }}
