apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-user-create"
  labels:
    {{- include "sentry.labels.standard" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-user-create"
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: user-create-job
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - sentry
            - createuser
            - --no-input
            - --email
            - $(SENTRY_ADMIN_EMAIL)
            - --superuser
            - --password
            - $(SENTRY_ADMIN_PASSWORD)
          env:
            {{- include "sentry.environment" . | nindent 12 }}
