apiVersion: v1
kind: SecretList
items:
  {{- $app := include "tls-certificates.name" . -}}
  {{- $chart := printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_") -}}
  {{- $release := .Release.Name -}}
  {{- $service := .Release.Service -}}
  {{- range $key, $value := .Values.certificates }}
  - apiVersion: v1
    kind: Secret
    metadata:
      name: {{ $key }}-tls
      labels:
        app: {{ $app }}
        chart: {{ $chart }}
        release: {{ $release }}
        heritage: {{ $service }}
        component: {{ $key }}
    type: Opaque
    data:
      tls.crt: {{ $value.crt | b64enc | quote }}
      tls.key: {{ $value.key | b64enc | quote }}
  {{- end }}
