apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cerebro.fullname" . }}
  labels:
    app: {{ template "cerebro.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  {{- if hasKey .Values.tls "files" }}
  {{- range $key, $value := .Values.tls.files }}
  certs-{{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if hasKey .Values.tls "base64Files" }}
  {{- range $key, $value := .Values.tls.base64Files }}
  certs-{{ $key }}: {{ $value | nospace | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
