{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ .Values.networkPolicy.apiVersion }}
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "jenkins.name" . }}
      component: {{ .Values.master.name }}
      release: {{ .Release.Name }}
  ingress:
    # Allow web access to the UI
    - ports:
      - port: {{ .Values.service.externalPort }}
    # Allow inbound connections from slave
    - from:
      - podSelector:
          matchLabels:
            "jenkins/{{ template "jenkins.agent.fullname" . }}": "true"
      ports:
      - port: {{ .Values.agent.listenerPort }}
{{- end }}
