{{- if .Values.master.useSecurity }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin-password: {{ .Values.master.adminPassword | default (randAlphaNum 10) | b64enc | quote }}
  admin-user: {{ .Values.master.adminUser | b64enc | quote }}
{{- end }}
