{{- if and .Values.ingress.enabled .Values.ingress.webhook.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}-webhook
  labels:
    app: {{ template "jenkins.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: webhook
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.service.webhook.annotations }}
  annotations:
    {{- toYaml .Values.service.webhook.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.webhook.type }}
  {{- if eq .Values.service.webhook.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.service.webhook.loadBalancerSourceRanges }}
  {{- end }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "jenkins.name" . }}
    component: {{ .Values.master.name }}
    release: {{ .Release.Name }}
{{- end -}}