dependencies:
  - name: postgresql
    version: 0.9.0
    repository: https://centerforopenscience.github.io/helm-charts/
    condition: postgresql.enabled, global.postgresql.enabled
  - name: redis
    version: 1.1.2
    repository: https://centerforopenscience.github.io/helm-charts/
    condition: redis.enabled, global.redis.enabled
