# Default values for echoserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: "gcr.io/google_containers/echoserver"
  tag: "1.5"
  pullPolicy: "IfNotPresent"

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  tls: []
    # - hosts:
    #   - echo.exmaple.com
    #   secretName: example-com-tls
  rules: []
    # - host: echo.example.com
