{{- if .Values.indexer.budget.minAvailable -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "share.indexer.fullname" . }}"
  labels:
    app: {{ template "share.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.indexer.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "share.name" . }}
      component: "{{ .Values.indexer.name }}"
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.indexer.budget.minAvailable }}
{{- end -}}
