dependencies:
  - name: elasticsearch
    version: 0.4.0
    repository: https://centerforopenscience.github.io/helm-charts/
    condition: elasticsearch.enabled, global.elasticsearch.enabled
  - name: postgresql
    version: 0.10.0
    repository: https://centerforopenscience.github.io/helm-charts/
    condition: postgresql.enabled, global.postgresql.enabled
  - name: rabbitmq
    version: 0.6.8
    repository: https://centerforopenscience.github.io/helm-charts/
    condition: rabbitmq.enabled, global.rabbitmq.enabled
