{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "osf.api.fullname" . }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.api.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    protocol: TCP
    name: {{ .Values.api.service.name }}
  selector:
    app: {{ template "osf.name" . }}
    component: "{{ .Values.api.name }}"
    release: {{ .Release.Name }}
{{- end -}}
