{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "osf.migration.fullname" . }}-{{ .Release.Time.Seconds }}
  labels:
    app: {{ template "osf.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: "{{ .Values.migration.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  activeDeadlineSeconds: 900
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app: {{ template "osf.name" . }}
        component: "{{ .Values.migration.name }}"
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/migration-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/migration-secret.yaml") . | sha256sum }}
        # Init containers not updated on upgrade : https://github.com/kubernetes/helm/issues/2702
        {{- if semverCompare "<1.8-0" .Capabilities.KubeVersion.GitVersion }}
        pod.alpha.kubernetes.io/init-containers: null
        pod.beta.kubernetes.io/init-containers: null
        {{- end }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: chown
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - chown -R www-data:www-data /log
          securityContext:
            runAsUser: 0
          volumeMounts:
            - mountPath: /log
              name: log
        {{- include "osf.certificates.initContainer" . | nindent 8 }}
      containers:
        - name: {{ .Values.migration.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |-
              PREFIX=''
              if [ -f /code/newrelic.ini ]; then
                PREFIX='newrelic-admin run-program'
              fi
              $PREFIX python manage.py sync_databases
              $PREFIX python -m scripts.register_oauth_scopes
              $PREFIX python -m scripts.populate_institutions nii
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: api.base.settings
            {{- include "osf.migration.environment" . | nindent 12 }}
            {{- range $key, $value := .Values.migration.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if or .Values.volumeMounts .Values.migration.volumeMounts }}
          volumeMounts:
            - mountPath: /log
              name: log
            {{- include "osf.volumeMounts" . | nindent 12 }}
            {{- if .Values.migration.volumeMounts }}
            {{- toYaml .Values.migration.volumeMounts | nindent 12 }}
            {{- end }}
          {{- end }}
      volumes:
        {{- include "osf.migration.volumes" . | nindent 8 }}
        - name: log
          {{- if .Values.migration.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.migration.persistence.existingClaim | default (include "osf.migration.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if .Values.migration.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.migration.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
{{- end -}}
