dependencies:
  - name: postgresql
    version: 0.8.1
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled, global.postgresql.enabled
  - name: rabbitmq
    version: 0.6.3
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: rabbitmq.enabled, global.rabbitmq.enabled
