apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sentry.fullname" . }}
  labels:
    {{- include "sentry.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secretEnvs }}
  {{ $key }}: {{ toString $value | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secretFiles }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
